name: python-intro-PGR
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.24.*
  - scipy
  - pandas=1.5.*
  - matplotlib=3.7.*
  - xlrd
  - openpyxl
  - notebook
  - scikit-learn
  - statsmodels
  - conda-forge:yfinance
  - conda-forge:nasdaq-data-link
  - pandas-datareader
  - pip
  - pip:
    - fredapi
